export const en = {
    'weibo':'weibo',
    'Cookbook':'Cookbook',
    'Donate':'Donate',
    'language':'language',
    'Welcome to 0xAdventure Guild. Receptionist – Telegram:@JJ_OntheRoad Smart tools supported by 0xAdventure, Enjoy free! All contracts have been verified in ftmscan. Use at your risk.':`Welcome to 0xAdventure Guild.<br /> Receptionist – <a href='https://t.me/JJ_OntheRoad' target='_blank'>Telegram:@JJ_OntheRoad</a><br /> Smart tools supported by 0xAdventure, Enjoy free! All contracts have been verified in ftmscan. Use at your risk.`,
    'Wallet Address:':'Wallet Address:',
    'Smart Adventure':'Smart Adventure',
    'Smart adventure can help you save much transaction fees.':'Smart adventure can help you save much transaction fees.',
    'Rarity contract address:':'Rarity contract address:',
    'Auto-adventure contract address':'Auto-adventure contract address',
    'Approval-For-All contract address':'Approval-For-All contract address',
    'Adventured ID':'Adventured ID',
    'Idle ID':'Idle ID',
    'Auto-adventure':'Auto-adventure',
    'If you have mass Summon heroes, try to break them up into dozens at a time. Note that multiple are separated by commas.':'If you have mass Summon heroes, try to break them up into dozens at a time. Note that multiple are separated by commas.',
    'Mass Recruit':'Mass Recruit',
    'You need to confirm in Metamask as many Summon heroes as you want to recruit':'You need to confirm in Metamask as many Summon heroes as you want to recruit',
    'Summoner Selection':'Summoner Selection',
    'Recruit Amount':'Recruit Amount',
    'Smart Level Up':'Smart Level Up',
    'Available Level Up IDs':'Available Level Up IDs',
    'If you have mass Summon heroes, try to break them up into dozens at a time. Note that multiple are separated by commas. No ids input will trigger all available ids.':'If you have mass Summon heroes, try to break them up into dozens at a time. Note that multiple are separated by commas. No ids input will trigger all available ids.',
    'Dungeon':'Dungeon',
    'Because of the restrictions of the Rarity logic, each ID needs approved. All approved ids can be worked in Dungeon, Gold Claim, Ability Score, etc. If you need please go to Approval-For-All first.':'Because of the restrictions of the Rarity logic, each ID needs approved. All approved ids can be worked in Dungeon, Gold Claim, Ability Score, etc. If you need please go to Approval-For-All first.',
    'Attack':'Attack',
    'loading':'loading',
    'Idle ids':'Idle ids',
    'Claim All Gold':'Claim All Gold',
    'Gold':'Gold',
    'Craft(Ⅰ)':'Craft(Ⅰ)',
    'Claimable':'Claimable',
    'Ability Score':'Ability Score',
    'Selected Summoner':'Selected Summoner',
    'Setting':'Setting',
    'Avaliable points':'Avaliable points',
    'Approval-For-All':'Approval-For-All',
    'Approval-For-All should be confirmed by Metamask 2 times. After that, no constraints with you in Dungeon, Gold Claim, Ability Score.':'Approval-For-All should be confirmed by Metamask 2 times. After that, no constraints with you in Dungeon, Gold Claim, Ability Score.',
    'Collect':'Collect',
    'Collect Materials':'Collect Materials',
    'Gold Transfer':'Gold Transfer',
    'Switch to':'Switch to',
    'Switch to Craft':'Switch to Craft',
    'Transfer a dozens of Gold':'Transfer a dozens of Gold',
    'Available IDs':'Available IDs',
    'Target ID':'Target ID',
    'Confirm':'Confirm',
    'Craft Transfer':'Craft Transfer',
    'Switch to Gold':'Switch to Gold',
    'Transfer a dozens of Craft Materials':'Transfer a dozens of Craft Materials',
    'Avaliable IDs':'Avaliable IDs',
    'If you have mass Summon heroes, try to break them up into dozens at a time. Note that multiple are separated by commas. And the times of confirmations corresponds to the ids.':'If you have mass Summon heroes, try to break them up into dozens at a time. Note that multiple are separated by commas. And the times of confirmations corresponds to the ids.',
    'Collect Summoners':'Collect Summoners',
    'Avaliable Summoners IDs':'Avaliable Summoners IDs',

    'Already adventured today':'Already adventured today！',
    'Loading':'Loading',
    'Please approve first':'Please approve first',
    'Transaction refused':'Transaction refused',
    'The fantom network error, please try again':'The fantom network error, please try again.',
    'Recommend Chrome':'Recommend Chrome',
    'Approve':'Approve',
    'Input RM ID':'Input RM ID',
    'Approved ID':'Approved ID',
    'Unapproved ID':'Unapproved ID',
    'None available ID to attack':'None available ID to attack',
    'Approve needed':'Approve needed',
    'Claim':'Claim',
    'None claimable ID':'None claimable ID',
    'Level up':'Level up',
    'None available ID to level up':'None available ID to level up',
    'Select an available Summoner to assign attributes':'Select an available Summoner to assign attributes',
    'Assigning attributes':'Assigning attributes',
    'Ability score can not be less than 8':'Ability score can not be less than 8',
    'Create at least 1':'Create at least 1',
    'Please select a Summoner':'Please select a Summoner',
    'Please input amount':'Please input amount',
    'Recriut':'Recriut',
    'You own the target ID':'You own the target ID',
    'The target ID is not of you, please confirm it':'The target ID is not of you, please confirm it.',
    'Please input target ID':'Please input target ID',
    'Please input tokenID':'Please input tokenID',
    'Please fill in the correct tokenID, separated by multiple commas':'Please fill in the correct tokenID, separated by multiple commas.',
    'Please input receive address':'Please input receive address',
    'Please input receive address-v1':'Please input receive address',
    'Cloak': 'Cloak',
    'Cloak Claim': 'Claim',
    'Invisibility Cloak': 'Invisibility Cloak',
    'Invisibility Cloak btn': 'Invisibility Cloak',
    'Owned cloaks': 'Cloak Token IDs',
    'Cloaks desc': 'Invisibility Cloak issued by Suterusu(https://suterusu.io/)',
    'Remaining cloaks': 'Cloak remaining'
}
