export const zh = {
    'weibo':'微博',
    'Cookbook':'保姆教程',
    'Donate':'打赏',
    'language':'选择语言',
    'Welcome to 0xAdventure Guild. Receptionist – Telegram:@JJ_OntheRoad Smart tools supported by 0xAdventure, Enjoy free! All contracts have been verified in ftmscan. Use at your risk.':'本工具由0xAdventure公会提供，免费且不收取任何服务费，谨防被骗。有问题加微信：cryptowhaler，进群成为公会一员，共同讨论。',
    'Wallet Address:':'当前地址：',
    'Smart Adventure':'一键冒险',
    'Smart adventure can help you save much transaction fees.':'一键冒险需要小狐狸授权，是调取Rarity官方自己的合约，比一个一个跑节省手续费',
    'Rarity contract address:':'Rarity合约代码:',
    'Auto-adventure contract address':'自动冒险合约代码',
    'Approval-For-All contract address':'批量授权合约代码',
    'Adventured ID':'已冒险ID',
    'Idle ID':'未冒险ID',
    'Auto-adventure':'自动冒险',
    'If you have mass Summon heroes, try to break them up into dozens at a time. Note that multiple are separated by commas.':'英雄数量太多的，每次复制几十个未冒险ID进去，一键冒险，注意多个用逗号分开',
    'Mass Recruit':'批量招募',
    'You need to confirm in Metamask as many Summon heroes as you want to recruit':'批量招募创建多少个，小狐狸就要确认多少次',
    'Summoner Selection':'选择角色',
    'Recruit Amount':'创建数量',
    'Smart Level Up':'一键升级',
    'Available Level Up IDs':'未升级ID',
    'If you have mass Summon heroes, try to break them up into dozens at a time. Note that multiple are separated by commas. No ids input will trigger all available ids.':'英雄数量太多的，每次复制几十个未升级D进去，注意多个用逗号分开，数量少的无需复制',
    'Dungeon':'一键副本',
    'Because of the restrictions of the Rarity logic, each ID needs approved. All approved ids can be worked in Dungeon, Gold Claim, Ability Score, etc. If you need please go to Approval-For-All first.':'因为官方合约的限制，每个ID都需要授权，之后授权过的ID可以批量挑战副本，副本、金币、加点授权共享，请先去批量授权',
    'Attack':'挑战',
    'loading':'加载中',
    'Idle ids':'未挑战',
    'Claim All Gold':'一键领金币',
    'Gold':'金币',
    'Craft(Ⅰ)':'肉',
    'Claimable':'未领取',
    'Ability Score':'一键加点',
    'Selected Summoner':'选择的角色',
    'Setting':'属性设定',
    'Avaliable points':'剩余可用点数',
    'Approval-For-All':'批量授权',
    'Approval-For-All should be confirmed by Metamask 2 times. After that, no constraints with you in Dungeon, Gold Claim, Ability Score.':'此功能针对副本、金币、加点进行批量授权，授权后可批量操作,首次要授权两次',
    'Collect Materials':'一键转金币&肉',
    'Gold Transfer':'你正在使用一键转金币',
    'Switch to Craft':'切换到一键转肉',
    'Transfer a dozens of Gold':'一键转金币',
    'Available IDs':'有金币ID:',
    'Target ID':'接受转账id：',
    'Confirm':'确认转账',
    'Craft Transfer':'你正在使用一键肉',
    'Switch to Gold':'切换到一键转金币',
    'Transfer a dozens of Craft Materials':'一键转肉',
    'Avaliable IDs':'有肉ID',
    'If you have mass Summon heroes, try to break them up into dozens at a time. Note that multiple are separated by commas. And the times of confirmations corresponds to the ids.':'英雄数量太多的，注意多个用逗号分开，输入多少个ID小狐狸就确认几次，注意去掉ID后面的数量',
    'If you have mass Summon heroes, try to break them up into dozens at a time':'英雄数量太多的，注意多个用逗号分开，输入多少个ID小狐狸就确认几次',
    'Collect Summoners':'一键转英雄',
    'Avaliable Summoners IDs':'所有英雄',

    'Already adventured today':'今日已冒险完！',
    'Loading':'数量越多加载越慢，稍等下',
    'Please approve first':'请先approve',
    'Transaction refused':'你拒绝了该笔交易',
    'The fantom network error, please try again':'访问节点异常，请重试',
    'Recommend Chrome':'建议使用chrome浏览器',
    'Approve':'授权',
    'Input RM ID':'请输入想要approve的tokenID',
    'Approved ID':'已授权ID',
    'Unapproved ID':'未授权ID',
    'None available ID to attack':'没有要挑战的ID',
    'Approve needed':'需要approve',
    'Claim':'领取',
    'None claimable ID':'没有要领取的ID',
    'Level up':'升级',
    'None available ID to level up':'没有要升级的ID',
    'Select an available Summoner to assign attributes':'请选择要加点的角色,并确认该角色满足加点条件',
    'Assigning attributes':'加点',
    'Ability score can not be less than 8':'点数不能小于8',
    'Create at least 1':'创建数量须大于0',
    'Please select a Summoner':'请选择角色',
    'Please input amount':'请选择输入创建数量',
    'Recriut':'招募',
    'You own the target ID':'接收id属于你',
    'The target ID is not of you, please confirm it':'接收id不属于你，确认后再转',
    'Please input target ID':'请填入接受金币的ID',
    'Please input tokenID':'请填入要转移的tokenID',
    'Please fill in the correct tokenID, separated by multiple commas':'请填入正确的tokenID，tokenID为数字，多个逗号分开',
    'Please input receive address':'请填入接受英雄的地址',
    'Please input receive address-v1':'接受转账地址',
    'Cloak': '斗篷',
    'Cloak Claim': '领取斗篷',
    'Invisibility Cloak': '斗篷',
    'Invisibility Cloak btn': '领取斗篷',
    'Owned cloaks': '已有斗篷ID',
    'Cloaks desc': '斗篷是由Suterusu(https://suterusu.io/)发行，0xAdventure只负责提供领取的便利性。',
    'Remaining cloaks': '剩余斗篷数量'
}
